### ISSUE TITLE
SyntaxError: invalid syntax with workflow.py

### ISSUE THREAD

**Issue by CH-DanLee** [TinderSec/gh-workflow-auditor#8]
Running pyyaml 6.0 and python 3.7

`python3 main.py build-and-release.yml`
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from auditor import content_analyzer
  File "/Applications/gh-workflow-auditor/auditor.py", line 1, in <module>
    from workflow import WorkflowParser, WorkflowVulnAudit
  File "/Applications/gh-workflow-auditor/workflow.py", line 60
    if matches := self.unsafe_input[regex].finditer(command_string):
                ^
SyntaxError: invalid syntax

**Comment by CH-DanLee** [comment]
Version and library path issues on local machine
